# Generated by Django 5.0.9 on 2026-08-17 14:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('lesson_opened', 'Yangi dars ochildi'), ('deadline_soon', 'Deadline yaqinlashdi'), ('homework_graded', 'Vazifa tekshirildi'), ('new_comment', 'Yangi izoh/javob'), ('payment_success', "To'lov muvaffaqiyatli"), ('certificate_ready', 'Sertifikat tayyor')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
